//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDCitasMedicasEntities1 : DbContext
    {
        public BDCitasMedicasEntities1()
            : base("name=BDCitasMedicasEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbCita> tbCita { get; set; }
        public virtual DbSet<tbErrorLog> tbErrorLog { get; set; }
        public virtual DbSet<tbEspecialidad> tbEspecialidad { get; set; }
        public virtual DbSet<tbHorarioMedico> tbHorarioMedico { get; set; }
        public virtual DbSet<tbMedico> tbMedico { get; set; }
        public virtual DbSet<tbPerfil> tbPerfil { get; set; }
        public virtual DbSet<tbUsuario> tbUsuario { get; set; }
    }
}
