//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCita
    {
        public int ConsecutivoCita { get; set; }
        public int ConsecutivoPaciente { get; set; }
        public int ConsecutivoMedico { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan HoraInicio { get; set; }
        public System.TimeSpan HoraFin { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
    
        public virtual tbMedico tbMedico { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
