//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbErrorLog
    {
        public int Id { get; set; }
        public System.DateTime FechaHora { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string Area { get; set; }
        public string Controlador { get; set; }
        public string Accion { get; set; }
        public string Mensaje { get; set; }
        public string StackTrace { get; set; }
        public string DataJson { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
